version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - docker build -t nasacrown .
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 337909777953.dkr.ecr.us-east-1.amazonaws.com)
      - docker tag nasacrown:latest 337909777953.dkr.ecr.us-east-1.amazonaws.com/nasacrown:latest
      - docker push 337909777953.dkr.ecr.us-east-1.amazonaws.com/nasacrown:latest

artifacts:
  files:
    - '**/*'
